// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chatroom struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Name      string
	Creator   string
}

type Message struct {
	ID        int64
	CreatedAt string
	Author    string
	Message   string
	RoomID    int64
}

type Todo struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Body      string
	Username  string
}

type Token struct {
	ID      int64
	JwtType string
	Jwt     string
	Valid   bool
	Family  pgtype.UUID
}

type User struct {
	CreatedAt         pgtype.Timestamptz
	Username          string
	Email             *string
	EncryptedPassword string
	PasswordCreatedAt pgtype.Timestamptz
	ID                pgtype.UUID
}

type UsersToken struct {
	ID      int64
	UserID  pgtype.UUID
	TokenID int64
}
