// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func AlertOnQueryParams(key string, value string, route string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_AlertOnQueryParams_46cd`,
		Function: `function __templ_AlertOnQueryParams_46cd(key, value, route){window.onload = function() {
    htmx.config.debug = true
    const params = new URLSearchParams(window.location.search);
    if (params.get(key) === value) {
      window.history.replaceState({}, document.title, "/");
      let element = document.getElementById("notification-container")
      if (element) {
        element.classList.remove("hidden")
      }
      htmx.ajax("GET", route, "#notification")
    }
  };}`,
		Call:       templ.SafeScript(`__templ_AlertOnQueryParams_46cd`, key, value, route),
		CallInline: templ.SafeScriptInline(`__templ_AlertOnQueryParams_46cd`, key, value, route),
	}
}
