// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func AlertOnQueryParams() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_AlertOnQueryParams_de5c`,
		Function: `function __templ_AlertOnQueryParams_de5c(){window.onload = function() {
  let potentials = {
    "unauthorized": ["true", "/alert/signout"],
    "signedout": ["true", "/alert/signout"],
    "404": ["true", "/alert/404"],
    "500": ["true", "/alert/500"],
  }
  const params = new URLSearchParams(window.location.search);

  // Iterate through the potentials object
  for (let key in potentials) {
    // Check if the current URL parameter matches the key in the potentials object
    if (params.has(key) && params.get(key) === potentials[key][0]) {
      window.history.replaceState({}, document.title, "/");
      document.getElementById("notification-container").classList.remove("hidden")

      let route = potentials[key][1];
      htmx.ajax("GET", route, "#notification");
      break
    }
  }
};}`,
		Call:       templ.SafeScript(`__templ_AlertOnQueryParams_de5c`),
		CallInline: templ.SafeScriptInline(`__templ_AlertOnQueryParams_de5c`),
	}
}
