// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: queries.sql

package sqlc

import (
	"context"
)

const allTodos = `-- name: AllTodos :many
SELECT id, created_at, body FROM todo LIMIT $1
`

func (q *Queries) AllTodos(ctx context.Context, limit int64) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, allTodos, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
